### ISSUE TITLE
LGUI/RGUI not working?

### ISSUE THREAD

**Issue by kevinmost** [cub-uanic/tmk_keyboard#20] opened 2015-02-26 05:33 UTC
I built this project successfully on Mac OS X Yosemite using the provided instructions. However, the LGUI and RGUI keys are never registered (regardless of where they are placed). All other keys function as expected. The keyboard was also tested on Linux and would not register LGUI and RGUI under this firmware.

On both the Mac and Linux machine, using Ben Blazak's stock Ergodox firmware (https://github.com/benblazak/ergodox-firmware) works fine including LGUI/RGUI.

If there's any other information or other files I can provide to be of assistance, I'd be happy to do so.

**Comment by kevinmost** [comment] 2015-02-26 18:12
Seems to have been an issue with my machine. It's working now, seemingly with no changes on my end (though I may have updated some `make`-related binaries at some point today).

**Comment by smgt** [comment] 2016-01-12 09:30
I'm experiencing the same problem @kevinmost. You don't remember what you did to solve the problem?

**Comment by kevinmost** [comment] 2016-01-12 13:45
I *think* it had to do with the `arm-none-eabi-gcc` version, but I'm not totally sure. I remember building on Linux made it work fine on both OS X and Linux.

**Comment by eltang** [comment] 2016-04-18 02:47
The problem is caused by your Boot Magic settings. Hold your Space and Backspace keys while plugging in your keyboard to clear them.

**Comment by squarefrog** [comment] 2016-06-06 08:06
I'm going to close this as it seems resolved. Feel free to open a new issue if you still have problems.

**Closed by squarefrog** 2016-06-06 08:06 UTC
